### ISSUE TITLE
Cannot find a develop branch in upstream, remote, or local repos.

### ISSUE THREAD

**Issue by don-radcliffe** [FISH497/assignment-2#3]
No pressure to address this on a weekend, but I'm not seeing a 'develop' branch anywhere, not in the upstream repo or my remote or local branches.  Everything else is looking right before that 'setting up the local branch' section of the example page.  Wondering if I'm missing something or if there's no 'develop' branch in the upstream repo?  I've attached screenshots of my RStudio and the upstream GitHubs repo page.  Thanks!

Don

![Capture](https://user-images.githubusercontent.com/18270826/105613861-0ff46400-5d7a-11eb-8ab8-5a9036611d66.JPG)
![Capture1](https://user-images.githubusercontent.com/18270826/105613862-108cfa80-5d7a-11eb-94a9-9305118f54ca.JPG)

**Comment by mdscheuerell** [comment]
Hi @don-radcliffe. You'll have to create the `develop` branch yourself, as mentioned in Task 3. If you need a reminder as to how to do that, check out the section on [Feature branches](https://fish497.github.io/website/lectures/week_03/lec_08_workflows_ex.html#Feature_branch_workflow) in the same notes.

**Comment by don-radcliffe** [comment]
Hi @mdscheuerell that was way too easy, no more Saturday homework for me!  Thanks for the help.
